#!/usr/bin/env python
# This file is part of Gmediafinder.

# Gmediafinder is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Gmediafinder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys, time

try:
        import Ubukey

except ImportError:
        raise SystemExit(' * Error: the "Ubukey" module is missing. If you did not install ubukey to /usr, you may need to add the appropriate site-packages directory to your PYTHONPATH')

from Ubukey import ubukey
ubukey.Ubukey_gui()

